### ISSUE TITLE
NullPointerException!! I got the log, but I don't think how it caused.

### ISSUE THREAD

**Issue by zewenwang** [youth5201314/banner#328]
The log is as follow.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setImageResource(int)' on a null object reference
	at com.youth.banner.Banner.onPageSelected(Banner.java:586)
	at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1967)
	at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:685)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:669)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
	at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:611)
	at com.youth.banner.Banner$1.run(Banner.java:465)
	at com.youth.banner.WeakHandler$WeakRunnable.run(WeakHandler.java:404)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6276)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)
```

`indicatorImages` only add newed imageview, so I am confused about the exception

**Comment by yansenkeler** [comment]
我也出现了这个问题

java.lang.RuntimeException:Unable to start activity ComponentInfo{com.lmm.ebay.facepay/com.lmm.ebay.facepay.pages.BigAdvActivity}: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class com.youth.banner.Banner
--
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2671)
3 ......
4 Caused by:
5 java.lang.NullPointerException:Attempt to invoke virtual method 'void android.widget.ImageView.setImageResource(int)' on a null object reference
6 com.youth.banner.Banner.initView(Banner.java:111)
7 com.youth.banner.Banner.<init>(Banner.java:96)
8 com.youth.banner.Banner.<init>(Banner.java:84)
9 java.lang.reflect.Constructor.newInstance0(Native Method)
10 java.lang.reflect.Constructor.newInstance(Constructor.java:430)
11 android.view.LayoutInflater.createView(LayoutInflater.java:645)
12 android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
13 android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
14 android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
15 android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
16 android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
17 android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
18 android.view.LayoutInflater.inflate(LayoutInflater.java:518)
19 android.view.LayoutInflater.inflate(LayoutInflater.java:426)
20 android.view.LayoutInflater.inflate(LayoutInflater.java:377)
21 android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
22 android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
23 com.lmm.ebay.facepay.pages.BigAdvActivity.onCreate(BigAdvActivity.java:131)
24 android.app.Activity.performCreate(Activity.java:6709)
25 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
26 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2624)
27 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2732)
28 android.app.ActivityThread.-wrap12(ActivityThread.java)
29 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
30 android.os.Handler.dispatchMessage(Handler.java:102)
31 android.os.Looper.loop(Looper.java:154)
32 android.app.ActivityThread.main(ActivityThread.java:6141)
33 java.lang.reflect.Method.invoke(Native Method)
34 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
35 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
